### PR TITLE
CGI Script

### LINKED ISSUE #10: CGI Script
Create a script to accept an HTTP request with an XML and XSL file, call Transformer with these files, and return the new XML file or an appropriate error.

- [x] Create the Python CGI script.
- [x] Test the application.
- [x] Document the API.
- [ ] Update the design document if needed.

Target development time: February 27, 2017 - March 6, 2017

### PR DESCRIPTION
**Pull request by pop**
# Status: Looking better!

fixes #10 

@shathaway some information about the usage of CGI scripts with Apache, or specifically `mod_fcgid`, would be much appreciated. If you think I should not use `mod_fcgid` I would appreciate some direction on which technology would be *best* to implement the common gateway between the user, apache, and our daemon.

## Progress Blocker: cannot get Apache to recognize simple CGI script

I am unable to get this pull request working. Help would be *much* appreciated.

The actual code between the daemon and the CGI script will be simple to write, I am currently having trouble setting up the CGI script in the first place. I am able to install Apache and get that working, but the actual CGI configuration is harder than expected.

1. The files (`xzes40-cgi.conf` and `xzes.py`) are copied to their `destination` described at the top of each file in a Debian Linux system with the packages outlined in `vagrant/setup.sh`.
2. The Apache service is restarted.
3. Running `curl localhost:8080` on the debian system results in a `403 Permission Denied` response from apache.

### CODE REVIEW

**Comment by shathaway** [comment]
Elija,

The apache web server modules: mod_cgi and mod_cgid

These are the easiest to implement.  For multi-threaded Apache Web Servers,
the mod_cgid is the default for MPM (Multi-Processing) Web Server.

The first link below is a tutorial on CGI.  The second link describes
some deployment information for MPM servers related to mod_cgid.


https://httpd.apache.org/docs/2.4/howto/cgi.html

https://httpd.apache.org/docs/2.4/mod/mod_cgid.html


Sincerely,
Steven J. Hathaway

**Comment by shathaway** [comment]
The Apache HTTPD has several modules for CGI scripts.  The default module is **mod_cgi**.  The multi-programming default module is **mod_cgid**.  Both these modules can be used to launch a basic CGI executable program.

A useful module **mod_wsgi** supports Python.  It is used by the Edgewall.org TRAC product. Its interface, however, is Python Class intensive.

I have had good prototyping results with ad-hoc web pages by creating static page templates whereby the CGI script performs content token substitution before sending the web page back to the user.  This eliminates much programming for full web page rendering.

Steve  Hathaway

**Comment by pop** [comment]
@shathaway Thank you for the response. I have a workable CGI script now which uses mod_cgi.

The purpose of the CGI script is to be an API that the website depends on. If we were rendering the entire webpage I would use something like mod_wsgi for templating, but for the time being I don't think we need to worry about that.

If that changes I will refactor the code to depend on mod_wsgi.

**Comment by pop** [comment]
@todouu Thank you for that fix. I'll be able to finish the CGI script now. 🙏

**Pull request merged**
