### PR TITLE
Initial travis CI addition

### PR DESCRIPTION
**Pull request by pop**
This Pull Request adds [Travis CI](https://travis-ci.org) to our project. This is useful because:

- We can ensure that code added to the project works without needing to run it ourselves.

@Todopen @zixunlu Please review the additions in this Pull Request and ask any questions you may have about what I have added and why. Please read the Travis CI website for more information about Continuous Integration.

### CODE REVIEW

**Comment by pop** [comment]
@Todopen @zixunlu To see the build output click `Show all checks` in the Pull Request information, then click `details` next to `continuous-integration/travis-ci/pr -- The Travis CI build passed`.

**Comment by todouu** [comment]
Ok, this sounds interesting. So we don't need even run our program in our virtual machine for our test, instead of go to Travis CI?

**Comment by pop** [comment]
@Todopen You (the developer) need to run the program in the virtual machine because this is very slow, but people checking your code can view if it is good or bad without needing to.

**Comment by pop** [comment]
@zixunlu Please comment.

**Comment by zixunlu** [comment]
The Travis CI is a great method.

**Comment by zixunlu** [comment]
The Travis CI is a great method and I will give a try for this.

**Comment by pop** [comment]
@Todopen @zixunlu Please merge this pull request.

**Pull request merged**
