### PR TITLE
Project structure

### PR DESCRIPTION
**Pull request by pop**
This includes any changes related to the project structure. It includes a Vagrant virtual machine and the simple project tree structure outline.

Please comment with any questions and feedback if you have any. We will merge this once the Winter term starts.

### CODE REVIEW

**Comment by pop** [comment]
@Todopen @zixunlu I would like you both to review this before the end of the weekend. Please comment with any confusion you have after reading the code and documentation. I will clarify the purpose, intention, and functionality in this Pull Request and in the documentation.

Also make sure that you can build the project on a Virtual Machine (the Vagrant one or the one provided by @shathaway).

I will merge this Monday morning if you do not have any questions so we can begin working on implementing features.

**Comment by todouu** [comment]
@ElijahCaine I have read whole document of our project. I think there is no confuse for me. By the way, which part is work for parallel computation?

**Comment by zixunlu** [comment]
ok I will try to use Vagrant

**Comment by pop** [comment]
@Todopen That information is in the design document.
@zixunlu If you have the VM from @shathaway you should be able to use that.

Merging now.

**Pull request merged**
