### PR TITLE
web interface

### PR DESCRIPTION
**Pull request by zixunlu**
The temporary website page is [http://web.engr.oregonstate.edu/~luzi/XZES40/XZES40.php](url)

### CODE REVIEW

**Comment by zixunlu** [comment]
I don't why the web page link can't be opened in the github. But you can copy the link to your chrome or firefox. It should be worked.

**Comment by pop** [comment]
Why is this written in PHP? It does not need to be written in PHP.

**Comment by pop** [comment]
The correct way to link this is by just putting the URL: http://web.engr.oregonstate.edu/~luzi/XZES40/XZES40.php

**Comment by pop** [comment]
@zixunlu 

# TODO: 
- [x] Place files in directory `xzes40/frontend`.
- [x] The buttons must allow me to select a file.
- [x] The form must be written to submit to an endpoint (for now it can redirect to itself).

**Comment by zixunlu** [comment]
The temporary website page changes to http://web.engr.oregonstate.edu/~luzi/XZES40/XZES40.html

**Comment by shathaway** [comment]
The temporary web page is not available via the Internet.  Users must have access to university resources.

**Comment by shathaway** [comment]
I tested an earlier web page.  The latest one displays via the Internet.
http://web.engr.oregonstate.edu/~luzi/XZES40/XZES40.html

**Comment by shathaway** [comment]
You may wish to add support for XSLT top-level parameters.  The StyleBook.xslt requires some top-level parameters.

**Comment by zixunlu** [comment]
I change the upload xml and xslt files forms. The user only can upload the xml file in "Upload your XML file" and upload the xslt file in "Upload your XSLT file".

**Pull request merged**
